// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using IDCL.Tacama.Core.Entity;
using Microsoft.EntityFrameworkCore;
#nullable enable

namespace IDCL.Tacama.Core.Contexto.IDCL.Tacama.Core.Contexto
{
    public partial class DbTacamaContext : DbContext
    {
        public DbTacamaContext()
        {
        }

        public DbTacamaContext(DbContextOptions<DbTacamaContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Rol> Rols { get; set; } = null!;
        public virtual DbSet<TramaDiario> TramaDiarios { get; set; } = null!;
        public virtual DbSet<TramaHistorico> TramaHistoricos { get; set; } = null!;
        public virtual DbSet<UsuarioTacama> Usuarios { get; set; } = null!;
        public virtual DbSet<UsuarioRol> UsuarioRols { get; set; } = null!;

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
        modelBuilder.ApplyConfiguration(new Configurations.RolConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.TramaDiarioConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.TramaHistoricoConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.UsuarioConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.UsuarioRolConfiguration());

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
