// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace IDCL.AVGUST.SIP.Contexto2.IDCL.AVGUST.SIP.Entity.Avgust
{
    public partial class Opcion
    {
        public Opcion()
        {
            InverseIdOpcionRefNavigation = new HashSet<Opcion>();
            PerfilOpcions = new HashSet<PerfilOpcion>();
        }

        public int Id { get; set; }
        public int IdAplicacion { get; set; }
        public string Nombre { get; set; } = null!;
        public string Type { get; set; } = null!;
        public string Url { get; set; } = null!;
        public string Icono { get; set; } = null!;
        public int Orden { get; set; }
        public int? IdOpcionRef { get; set; }
        public bool FlgActivo { get; set; }

        public virtual Opcion? IdOpcionRefNavigation { get; set; }
        public virtual ICollection<Opcion> InverseIdOpcionRefNavigation { get; set; }
        public virtual ICollection<PerfilOpcion> PerfilOpcions { get; set; }
    }
}