// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace IDCL.AVGUST.SIP.Contexto2.IDCL.AVGUST.SIP.Entity.Avgust
{
    public partial class Perfil
    {
        public Perfil()
        {
            PerfilOpcions = new HashSet<PerfilOpcion>();
            UsuarioPerfils = new HashSet<UsuarioPerfil>();
        }

        public int Id { get; set; }
        public string Nombre { get; set; } = null!;
        public bool FlgActivo { get; set; }

        public virtual ICollection<PerfilOpcion> PerfilOpcions { get; set; }
        public virtual ICollection<UsuarioPerfil> UsuarioPerfils { get; set; }
    }
}