// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

namespace IDCL.Tacama.Core.Entity
{
    public partial class TramaHistorico
    {
        public long Id { get; set; }
        public int IdPersona { get; set; }
        public DateTime FechaHora { get; set; }
        public decimal Longitud { get; set; }
        public decimal Latitud { get; set; }
    }
}