// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

namespace IDCL.AVGUST.SIP.Entity.Pedido
{
    public partial class PedidoCab
    {
        public int IdPedido { get; set; }
        public int IdEmpresa { get; set; }
        public int IdLocal { get; set; }
        public int CodPedido { get; set; }
        public string? CodPedidoCad { get; set; }
        public DateTime Fecha { get; set; }
        /// <summary>
        /// id de Consignatario
        /// </summary>
        public int? IdConsignatario { get; set; }
        /// <summary>
        /// id Notificar a las partes
        /// </summary>
        public int? IdNotificar { get; set; }
        /// <summary>
        /// id de Consignatario FitoSanitario
        /// </summary>
        public int? IdConsFitosanitario { get; set; }
        /// <summary>
        /// id para Facturar
        /// </summary>
        public int IdFacturar { get; set; }
        /// <summary>
        /// id de Broker
        /// </summary>
        public int? IdBroker { get; set; }
        /// <summary>
        /// id de Semana
        /// </summary>
        public int? IdSemanaEmbarque { get; set; }
        /// <summary>
        /// Pais Origen
        /// </summary>
        public int? IdPaisOrigen { get; set; }
        /// <summary>
        /// id de Origen  Ejemplo Callao Peru
        /// </summary>
        public int? IdOrigen { get; set; }
        /// <summary>
        /// Pais Destino
        /// </summary>
        public int? IdPaisDestino { get; set; }
        /// <summary>
        /// id de Destino Honk Kong
        /// </summary>
        public int? IdDestino { get; set; }
        /// <summary>
        /// id Flete Ejemplo Collect
        /// </summary>
        public int? IdFlete { get; set; }
        /// <summary>
        /// id Ejemplo SEA WILL BILL
        /// </summary>
        public int? IdBlEmision { get; set; }
        /// <summary>
        /// id MG
        /// </summary>
        public int? IdTipoCompra { get; set; }
        /// <summary>
        /// Incoterms FOB CALLAO
        /// </summary>
        public int? IdIncoterms { get; set; }
        public int? IdIncotermsPrecio { get; set; }
        public string? IdMoneda { get; set; }
        public string? Observacion { get; set; }
        public string? Indicaciones { get; set; }
        /// <summary>
        /// Operador Logistico
        /// </summary>
        public int? IdOperador { get; set; }
        /// <summary>
        /// Estado de Pedido P=Pendiente, C=Cerrado
        /// </summary>
        public string Estado { get; set; } = null!;
        /// <summary>
        /// Numero de Reserva / Booking
        /// </summary>
        public string? Reserva { get; set; }
        /// <summary>
        /// Naviera
        /// </summary>
        public int? IdNaviera { get; set; }
        /// <summary>
        /// Fecha Estimada de Llegada
        /// </summary>
        public DateTime? Eta { get; set; }
        /// <summary>
        /// Fecha Estimada de Salida
        /// </summary>
        public DateTime? Etd { get; set; }
        public string? Barco { get; set; }
        /// <summary>
        /// Almacen de Ingreso de Contenedor
        /// </summary>
        public int? AlmacenIngreso { get; set; }
        /// <summary>
        /// Fecha de Posicionamiento Contenedor
        /// </summary>
        public DateTime? FechaPosic { get; set; }
        /// <summary>
        /// Fecha de Inspeccion
        /// </summary>
        public DateTime? FechaInspeccion { get; set; }
        /// <summary>
        /// Contenedor
        /// </summary>
        public string? Contenedor { get; set; }
        /// <summary>
        /// Numero de Termografo
        /// </summary>
        public string? TermografosNum { get; set; }
        /// <summary>
        /// Termografo 2
        /// </summary>
        public string? TermografosNum2 { get; set; }
        /// <summary>
        /// Ubicacion de Termografo
        /// </summary>
        public string? TermografosUbi { get; set; }
        /// <summary>
        /// Ubicacion de Termografo2
        /// </summary>
        public string? TermografosUbi2 { get; set; }
        /// <summary>
        /// Precinto Operador
        /// </summary>
        public string? PrecintoOperador { get; set; }
        /// <summary>
        /// Precinto Naviera
        /// </summary>
        public string? PrecintoNaviera { get; set; }
        /// <summary>
        /// Precinto Senasa
        /// </summary>
        public string? PrecintoSenasa { get; set; }
        /// <summary>
        /// Precinto Aduana
        /// </summary>
        public string? PrecintoAduana { get; set; }
        /// <summary>
        /// Precinto Otros
        /// </summary>
        public string? PrecintoOtro { get; set; }
        /// <summary>
        /// Numero de Guia de Despacho
        /// </summary>
        public string? NroGuia { get; set; }
        public string? NroDocReferencia { get; set; }
        public DateTime? FecFactura { get; set; }
        public string? NroFactura { get; set; }
        public string? NroBl { get; set; }
        public string? NroDam { get; set; }
        public int? IdFormaPago { get; set; }
        public int? IdTipCondicion { get; set; }
        public int? IdCondicion { get; set; }
        public bool? IndDsctoProntoPago { get; set; }
        public decimal? DsctoProntoPago { get; set; }
        public bool? IndBonificacion { get; set; }
        public bool? IndObsStock { get; set; }
        public string? ObsStock { get; set; }
        public bool? IndObsCredito { get; set; }
        public string? ObsCredito { get; set; }
        public int? IdVendedor { get; set; }
        /// <summary>
        /// Zona de Trabajo
        /// </summary>
        public int? IdEstablecimiento { get; set; }
        /// <summary>
        /// Zona de Trabajo
        /// </summary>
        public int? IdZona { get; set; }
        /// <summary>
        /// 0 = Nacional 1 = Exportacion
        /// </summary>
        public bool? Tipo { get; set; }
        public decimal? TotsubTotal { get; set; }
        public decimal? TotDscto1 { get; set; }
        public decimal? TotDscto2 { get; set; }
        public decimal? TotDscto3 { get; set; }
        public decimal? TotIsc { get; set; }
        public decimal? TotIgv { get; set; }
        public decimal? TotTotal { get; set; }
        public int? IdSucursalCliente { get; set; }
        public string? PuntoPartida { get; set; }
        public string? PuntoLlegada { get; set; }
        public string? Referencia { get; set; }
        public string? Contacto { get; set; }
        public string? Telefono { get; set; }
        public string? Correo { get; set; }
        public DateTime? FechaEntrega { get; set; }
        public string? HorarioEntrega { get; set; }
        public bool? EsAnticipo { get; set; }
        public int? TipoDoc { get; set; }
        public int? IdTransporte { get; set; }
        public string? IndCotPed { get; set; }
        public int? IdPedidoEnlace { get; set; }
        public string? TipoGeneracion { get; set; }
        public int? IdDivision { get; set; }
        public int? IdCanalVenta { get; set; }
        public decimal? PorDscto { get; set; }
        public bool? FlagListaActivo { get; set; }
        public int? IdListaPrecio { get; set; }
        public bool? CorreoEnviado { get; set; }
        public bool? IndFechaFinReserva { get; set; }
        public DateTime? FechaFinReserva { get; set; }
        public string? UsuarioGen { get; set; }
        public DateTime? FechaGen { get; set; }
        public string? NroGuiaGen { get; set; }
        public string? NroFacturaGen { get; set; }
        public int? Aprobacion { get; set; }
        public string? MensajeAprobacion { get; set; }
        public string? IdMonedaLineaCredito { get; set; }
        public decimal? TipCambio { get; set; }
        public decimal? LineaCredito { get; set; }
        public decimal? CreditoLetras { get; set; }
        public decimal? CreditoFacturas { get; set; }
        public decimal? CreditoDocumento { get; set; }
        public decimal? LineaDisponible { get; set; }
        public string? OrdenDeCompraNum { get; set; }
        public decimal? LetraNoAceptadas { get; set; }
        public decimal? LetraProtestadas { get; set; }
        public int? IdiomaImpresion { get; set; }
        public int? IdContacto { get; set; }
        public string? PuertoOrigen { get; set; }
        public string? PuertoDestino { get; set; }
        public int? DiasValidez { get; set; }
        public int? AprobacionPrecios { get; set; }
        public string? MensajeAprobacionPrecios { get; set; }
        public bool? IndAgencia { get; set; }
        public int? IdAgenciaEnvio { get; set; }
        public int? IdDireccion { get; set; }
        public string? UbigeoCot { get; set; }
        public string? UsuarioRegistro { get; set; }
        public DateTime? FechaRegistro { get; set; }
        public string? UsuarioModificacion { get; set; }
        public DateTime? FechaModificacion { get; set; }

        public List<PedidoDet> PedidoDets { get; set; }
    }
}