// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

namespace IDCL.AVGUST.SIP.Entity.Pedido
{
    public partial class TipoCambio
    {
        public int IdCambio { get; set; }
        public string IdMoneda { get; set; } = null!;
        public DateTime FecCambio { get; set; }
        public decimal? ValVenta { get; set; }
        public decimal? ValCompra { get; set; }
        public decimal? ValVentaCaja { get; set; }
        public decimal? ValCompraCaja { get; set; }
        public string? UsuarioRegistro { get; set; }
        public DateTime? FechaRegistro { get; set; }
        public string? UsuarioModificacion { get; set; }
        public DateTime? FechaModificacion { get; set; }
    }
}