// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using IDCL.AVGUST.SIP.Entity.Calculator;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

#nullable disable

namespace IDCL.AVGUST.SIP.Contextos.IDCL.AVGUST.SIP.Contexto.Configurations
{
    public partial class ArticuloServConfiguration : IEntityTypeConfiguration<ArticuloServ>
    {
        public void Configure(EntityTypeBuilder<ArticuloServ> entity)
        {
            entity.HasKey(e => new { e.IdEmpresa, e.IdArticulo });

            entity.ToTable("ArticuloServ");

            entity.Property(e => e.IdEmpresa).HasColumnName("idEmpresa");

            entity.Property(e => e.IdArticulo)
                .ValueGeneratedOnAdd()
                .HasColumnName("idArticulo");

            entity.Property(e => e.AltPlataforma).HasColumnType("decimal(12, 2)");

            entity.Property(e => e.Ancho).HasColumnType("decimal(16, 2)");

            entity.Property(e => e.BolExterno).HasColumnType("decimal(12, 2)");

            entity.Property(e => e.BolInterno).HasColumnType("decimal(12, 2)");

            entity.Property(e => e.Calibre).HasColumnType("decimal(16, 2)");

            entity.Property(e => e.Capacidad)
                .HasColumnType("decimal(15, 3)")
                .HasDefaultValueSql("((0))");

            entity.Property(e => e.CodArticulo)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("codArticulo");

            entity.Property(e => e.CodBarra)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("codBarra");

            entity.Property(e => e.CodBarra2)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("codBarra2");

            entity.Property(e => e.CodBarra3)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("codBarra3");

            entity.Property(e => e.CodBarra4)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("codBarra4");

            entity.Property(e => e.CodBarra5)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("codBarra5");

            entity.Property(e => e.CodCapellada).HasColumnName("codCapellada");

            entity.Property(e => e.CodCategoria)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("codCategoria");

            entity.Property(e => e.CodColor).HasColumnName("codColor");

            entity.Property(e => e.CodEquivalente)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.CodEstacion).HasColumnName("codEstacion");

            entity.Property(e => e.CodEstilo).HasColumnName("codEstilo");

            entity.Property(e => e.CodForro).HasColumnName("codForro");

            entity.Property(e => e.CodLineaVenta)
                .HasMaxLength(2)
                .IsUnicode(false)
                .HasColumnName("codLineaVenta");

            entity.Property(e => e.CodMarca).HasColumnName("codMarca");

            entity.Property(e => e.CodMaterial).HasColumnName("codMaterial");

            entity.Property(e => e.CodModelo).HasColumnName("codModelo");

            entity.Property(e => e.CodPlanta).HasColumnName("codPlanta");

            entity.Property(e => e.CodSerie).HasColumnName("codSerie");

            entity.Property(e => e.CodTaco).HasColumnName("codTaco");

            entity.Property(e => e.CodTipoMedAlmacen).HasColumnName("codTipoMedAlmacen");

            entity.Property(e => e.CodTipoMedPresentacion).HasColumnName("codTipoMedPresentacion");

            entity.Property(e => e.CodUniMedAlmacen).HasColumnName("codUniMedAlmacen");

            entity.Property(e => e.CodUniMedPresentacion).HasColumnName("codUniMedPresentacion");

            entity.Property(e => e.CodigoSunat)
                .HasMaxLength(10)
                .IsUnicode(false);

            entity.Property(e => e.Compartimiento).HasColumnType("decimal(12, 2)");

            entity.Property(e => e.Contenido)
                .HasColumnType("decimal(15, 2)")
                .HasDefaultValueSql("((0))");

            entity.Property(e => e.DensidadDesde).HasColumnType("decimal(18, 2)");

            entity.Property(e => e.DensidadHasta).HasColumnType("decimal(18, 2)");

            entity.Property(e => e.DesColor)
                .HasMaxLength(500)
                .IsUnicode(false);

            entity.Property(e => e.Extension)
                .HasMaxLength(5)
                .IsUnicode(false);

            entity.Property(e => e.FecCese)
                .HasColumnType("datetime")
                .HasColumnName("fecCese");

            entity.Property(e => e.FechaModificacion).HasColumnType("smalldatetime");

            entity.Property(e => e.FechaRegistro).HasColumnType("smalldatetime");

            entity.Property(e => e.FlagActivo).HasColumnName("flagActivo");

            entity.Property(e => e.Gramaje).HasColumnType("decimal(16, 2)");

            entity.Property(e => e.Horma)
                .HasMaxLength(2)
                .IsUnicode(false);

            entity.Property(e => e.IdArticuloBase).HasColumnName("idArticuloBase");

            entity.Property(e => e.IdConcepto).HasColumnName("idConcepto");

            entity.Property(e => e.IdPresentacion).HasColumnName("idPresentacion");

            entity.Property(e => e.IdTipo).HasColumnName("idTipo");

            entity.Property(e => e.IdTipoArticulo).HasColumnName("idTipoArticulo");

            entity.Property(e => e.IdTipoMedEnvase).HasColumnName("idTipoMedEnvase");

            entity.Property(e => e.IdUniMedEnvase).HasColumnName("idUniMedEnvase");

            entity.Property(e => e.Idformato).HasColumnName("idformato");

            entity.Property(e => e.IndAfectoIgv).HasColumnName("indAfectoIgv");

            entity.Property(e => e.IndAfectoIsc).HasColumnName("indAfectoIsc");

            entity.Property(e => e.IndCodBarra).HasColumnName("indCodBarra");

            entity.Property(e => e.IndCodEquivalente).HasColumnName("indCodEquivalente");

            entity.Property(e => e.IndCodSunat).HasColumnName("indCodSunat");

            entity.Property(e => e.IndCompraDemasia).HasColumnName("indCompraDemasia");

            entity.Property(e => e.IndConcepto)
                .HasColumnName("indConcepto")
                .HasDefaultValueSql("((0))");

            entity.Property(e => e.IndCuero).HasColumnName("indCuero");

            entity.Property(e => e.IndDetraccion).HasColumnName("indDetraccion");

            entity.Property(e => e.IndLineaVenta)
                .HasColumnName("indLineaVenta")
                .HasDefaultValueSql("((0))");

            entity.Property(e => e.IndMedida).HasColumnName("indMedida");

            entity.Property(e => e.Largo).HasColumnType("decimal(16, 2)");

            entity.Property(e => e.MedAncho).HasColumnType("decimal(12, 2)");

            entity.Property(e => e.MedLargo).HasColumnType("decimal(12, 2)");

            entity.Property(e => e.NomArticulo)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("nomArticulo");

            entity.Property(e => e.NomArticuloEng)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("nomArticuloEng");

            entity.Property(e => e.NomArticuloLargo)
                .HasMaxLength(500)
                .IsUnicode(false)
                .HasColumnName("nomArticuloLargo");

            entity.Property(e => e.NomCorto)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("nomCorto");

            entity.Property(e => e.NombreImagen)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.NombreReal)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.PesoUnitario).HasColumnType("decimal(18, 6)");

            entity.Property(e => e.PhDesde).HasColumnType("decimal(18, 2)");

            entity.Property(e => e.PhHasta).HasColumnType("decimal(18, 2)");

            entity.Property(e => e.PorcentajeDemasia).HasColumnType("decimal(6, 2)");

            entity.Property(e => e.Sku)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("SKU");

            entity.Property(e => e.TipDetraccion)
                .HasMaxLength(3)
                .IsUnicode(false)
                .HasColumnName("tipDetraccion");

            entity.Property(e => e.UsuarioModificacion)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.UsuarioRegistro)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.ArticuloCategorium)
                .WithMany(p => p.ArticuloServs)
                .HasForeignKey(d => new { d.IdEmpresa, d.IdTipoArticulo, d.CodCategoria })
                .HasConstraintName("FK_ArticuloServ_Articulo_Categoria");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ArticuloServ> entity);
    }
}
