// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using IDCL.AVGUST.SIP.Entity.Calculator;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

#nullable disable

namespace IDCL.AVGUST.SIP.Contextos.IDCL.AVGUST.SIP.Contexto.Configurations
{
    public partial class ArticuloCategoriumConfiguration : IEntityTypeConfiguration<ArticuloCategorium>
    {
        public void Configure(EntityTypeBuilder<ArticuloCategorium> entity)
        {
            entity.HasKey(e => new { e.IdEmpresa, e.IdTipoArticulo, e.CodCategoria });

            entity.ToTable("Articulo_Categoria");

            entity.Property(e => e.IdEmpresa).HasColumnName("idEmpresa");

            entity.Property(e => e.IdTipoArticulo).HasColumnName("idTipoArticulo");

            entity.Property(e => e.CodCategoria)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.CodCategoriaAnte)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.CodCategoriaAsoc)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("codCategoriaAsoc");

            entity.Property(e => e.CodCategoriaSup)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.CodCuentaAdm)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("codCuentaAdm");

            entity.Property(e => e.CodCuentaCompra)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("codCuentaCompra");

            entity.Property(e => e.CodCuentaConsumo)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("codCuentaConsumo");

            entity.Property(e => e.CodCuentaPorRecibir)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("codCuentaPorRecibir");

            entity.Property(e => e.CodCuentaPro)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("codCuentaPro");

            entity.Property(e => e.CodCuentaVenta)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("codCuentaVenta");

            entity.Property(e => e.CodCuentaVenta12)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("codCuentaVenta12");

            entity.Property(e => e.CodCuentaVentaRelacionada)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("codCuentaVentaRelacionada");

            entity.Property(e => e.CodCuentaVta)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("codCuentaVta");

            entity.Property(e => e.FechaModificacion).HasColumnType("smalldatetime");

            entity.Property(e => e.FechaRegistro).HasColumnType("smalldatetime");

            entity.Property(e => e.IdTipoArticuloAsoc).HasColumnName("idTipoArticuloAsoc");

            entity.Property(e => e.IndCuenta).HasColumnName("indCuenta");

            entity.Property(e => e.IndManejaUnmMayor)
                .HasColumnName("indManejaUnmMayor")
                .HasDefaultValueSql("((1))");

            entity.Property(e => e.IndManejaUnmMenor)
                .HasColumnName("indManejaUnmMenor")
                .HasDefaultValueSql("((0))");

            entity.Property(e => e.IndUltimoNivel)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("indUltimoNivel")
                .IsFixedLength();

            entity.Property(e => e.NombreCategoria)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("nombre_categoria");

            entity.Property(e => e.NumNivel).HasColumnName("numNivel");

            entity.Property(e => e.NumVerPlanCuentas)
                .HasMaxLength(3)
                .IsUnicode(false)
                .HasColumnName("numVerPlanCuentas");

            entity.Property(e => e.UsuarioModificacion)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.UsuarioRegistro)
                .HasMaxLength(20)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ArticuloCategorium> entity);
    }
}
