// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using IDCL.AVGUST.SIP.Entity.Calculator;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

#nullable disable

namespace IDCL.AVGUST.SIP.Contextos.IDCL.AVGUST.SIP.Contexto.Configurations
{
    public partial class ListaPrecioConfiguration : IEntityTypeConfiguration<ListaPrecio>
    {
        public void Configure(EntityTypeBuilder<ListaPrecio> entity)
        {
            entity.HasKey(e => new { e.IdEmpresa, e.IdListaPrecio });

            entity.ToTable("ListaPrecio");

            entity.Property(e => e.IdEmpresa).HasColumnName("idEmpresa");

            entity.Property(e => e.IdListaPrecio)
                .ValueGeneratedOnAdd()
                .HasColumnName("idListaPrecio");

            entity.Property(e => e.FechaBaja).HasColumnType("smalldatetime");

            entity.Property(e => e.FechaModificacion).HasColumnType("smalldatetime");

            entity.Property(e => e.FechaRegistro).HasColumnType("smalldatetime");

            entity.Property(e => e.IdMoneda)
                .HasMaxLength(2)
                .IsUnicode(false)
                .HasColumnName("idMoneda")
                .IsFixedLength();

            entity.Property(e => e.IndBaja).HasColumnName("indBaja");

            entity.Property(e => e.Nombre)
                .HasMaxLength(150)
                .IsUnicode(false);

            entity.Property(e => e.NombreCorto)
                .HasMaxLength(10)
                .IsUnicode(false);

            entity.Property(e => e.NroLista).HasDefaultValueSql("((0))");

            entity.Property(e => e.UsuarioModificacion)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.UsuarioRegistro)
                .HasMaxLength(20)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ListaPrecio> entity);
    }
}
