// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using IDCL.AVGUST.SIP.Entity.Calculator;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

#nullable disable

namespace IDCL.AVGUST.SIP.Contextos.IDCL.AVGUST.SIP.Contexto.Configurations
{
    public partial class ListaPrecioItemDetConfiguration : IEntityTypeConfiguration<ListaPrecioItemDet>
    {
        public void Configure(EntityTypeBuilder<ListaPrecioItemDet> entity)
        {
            entity.HasKey(e => new { e.IdEmpresa, e.IdListaPrecio, e.Item, e.Iditem });

            entity.ToTable("ListaPrecioItemDet");

            entity.Property(e => e.IdEmpresa).HasColumnName("idEmpresa");

            entity.Property(e => e.IdListaPrecio).HasColumnName("idListaPrecio");

            entity.Property(e => e.Item).HasColumnName("item");

            entity.Property(e => e.Iditem)
                .ValueGeneratedOnAdd()
                .HasColumnName("iditem");

            entity.Property(e => e.DesdeCantidad)
                .HasColumnType("decimal(16, 4)")
                .HasDefaultValueSql("((0))");

            entity.Property(e => e.FechaModificacion).HasColumnType("smalldatetime");

            entity.Property(e => e.FechaRegistro).HasColumnType("smalldatetime");

            entity.Property(e => e.IdArticulo).HasColumnName("idArticulo");

            entity.Property(e => e.IdTipoArticulo).HasColumnName("idTipoArticulo");

            entity.Property(e => e.PrecioBruto)
                .HasColumnType("decimal(10, 2)")
                .HasDefaultValueSql("((0))");

            entity.Property(e => e.PrecioVenta).HasColumnType("decimal(10, 2)");

            entity.Property(e => e.UsuarioModificacion)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.UsuarioRegistro)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.ListaPrecioItem)
                .WithMany(p => p.ListaPrecioItemDets)
                .HasForeignKey(d => new { d.IdEmpresa, d.IdListaPrecio, d.Item })
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ListaPrecioItemDet_ListaPrecioItem");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ListaPrecioItemDet> entity);
    }
}
