// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using IDCL.AVGUST.SIP.Entity.Calculator;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

#nullable disable

namespace IDCL.AVGUST.SIP.Contextos.IDCL.AVGUST.SIP.Contexto.Configurations
{
    public partial class RentabilidadComisionConfiguration : IEntityTypeConfiguration<RentabilidadComision>
    {
        public void Configure(EntityTypeBuilder<RentabilidadComision> entity)
        {
            entity.HasKey(e => new { e.IdEmpresa, e.Anio, e.Mes, e.IdArticulo });

            entity.ToTable("RentabilidadComision");

            entity.Property(e => e.IdEmpresa).HasColumnName("idEmpresa");

            entity.Property(e => e.Anio)
                .HasMaxLength(4)
                .IsUnicode(false)
                .HasColumnName("anio");

            entity.Property(e => e.Mes)
                .HasMaxLength(2)
                .IsUnicode(false)
                .HasColumnName("mes");

            entity.Property(e => e.IdArticulo).HasColumnName("idArticulo");

            //entity.Property(e => e.IdAlmacen).HasColumnName("idAlmacen");

            entity.Property(e => e.CategoriaRes).HasColumnType("decimal(16, 2)");

            entity.Property(e => e.CostoUnit).HasColumnType("decimal(16, 2)");

            entity.Property(e => e.FechaModificacion).HasColumnType("smalldatetime");

            entity.Property(e => e.FechaRegistro).HasColumnType("smalldatetime");

            entity.Property(e => e.Porcentaje).HasColumnType("decimal(16, 2)");

            entity.Property(e => e.UsuarioModificacion)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.UsuarioRegistro)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.Id)
                .WithMany(p => p.RentabilidadComisions)
                .HasForeignKey(d => new { d.IdEmpresa, d.IdArticulo })
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RentabilidadComision_ArticuloServ");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<RentabilidadComision> entity);
    }
}
