// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using IDCL.AVGUST.SIP.Entity.Calculator;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

#nullable disable

namespace IDCL.AVGUST.SIP.Contextos.IDCL.AVGUST.SIP.Contexto.Configurations
{
    public partial class SimuladorPedidoItemConfiguration : IEntityTypeConfiguration<SimuladorPedidoItem>
    {
        public void Configure(EntityTypeBuilder<SimuladorPedidoItem> entity)
        {
            entity.HasKey(e => new { e.IdPedido, e.IdArticulo });

            entity.ToTable("SimuladorPedidoItem");

            entity.Property(e => e.Codigo)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.CodigoFamilia)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.ComisionPercent).HasColumnType("decimal(18, 3)");

            entity.Property(e => e.Costo).HasColumnType("decimal(18, 3)");

            entity.Property(e => e.Familia)
                .HasMaxLength(300)
                .IsUnicode(false);

            entity.Property(e => e.Importe).HasColumnType("decimal(18, 3)");

            entity.Property(e => e.Mb)
                .HasColumnType("decimal(18, 3)")
                .HasColumnName("mb");

            entity.Property(e => e.PartImporteTotal).HasColumnType("decimal(18, 3)");

            entity.Property(e => e.PesoAsignadoPercent).HasColumnType("decimal(18, 3)");

            entity.Property(e => e.PrecioVvd)
                .HasColumnType("decimal(18, 3)")
                .HasColumnName("PrecioVVD");

            entity.Property(e => e.Producto)
                .HasMaxLength(300)
                .IsUnicode(false);

            entity.HasOne(d => d.IdPedidoNavigation)
                .WithMany(p => p.SimuladorPedidoItems)
                .HasForeignKey(d => d.IdPedido)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SimuladorPedidoItem_SimuladorPedido");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<SimuladorPedidoItem> entity);
    }
}
