// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using IDCL.AVGUST.SIP.Entity.Calculator;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

#nullable disable

namespace IDCL.AVGUST.SIP.Contextos.IDCL.AVGUST.SIP.Contexto.Configurations
{
    public partial class SimuladorPedidoConfiguration : IEntityTypeConfiguration<SimuladorPedido>
    {
        public void Configure(EntityTypeBuilder<SimuladorPedido> entity)
        {
            entity.HasKey(e => e.IdPedido);

            entity.ToTable("SimuladorPedido");

            entity.Property(e => e.ComisionMonto).HasColumnType("decimal(9, 3)");

            entity.Property(e => e.ComisionPercent).HasColumnType("decimal(9, 3)");

            entity.Property(e => e.FechaOperacion).HasColumnType("datetime");

            entity.Property(e => e.Igv)
                .HasColumnType("decimal(18, 3)")
                .HasColumnName("igv");

            entity.Property(e => e.ImporteTotal).HasColumnType("decimal(18, 3)");

            entity.Property(e => e.VentaTotal).HasColumnType("decimal(18, 3)");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<SimuladorPedido> entity);
    }
}
