// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using IDCL.AVGUST.SIP.Entity.Calculator;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

#nullable disable

namespace IDCL.AVGUST.SIP.Contextos.IDCL.AVGUST.SIP.Contexto.Configurations
{
    public partial class TasasComisionConfiguration : IEntityTypeConfiguration<TasasComision>
    {
        public void Configure(EntityTypeBuilder<TasasComision> entity)
        {
            entity.HasKey(e => e.Categoria);

            entity.ToTable("TasasComision");

            entity.Property(e => e.Categoria)
                .HasMaxLength(10)
                .IsUnicode(false);

            entity.Property(e => e.FechaModificacion).HasColumnType("smalldatetime");

            entity.Property(e => e.FechaRegistro).HasColumnType("smalldatetime");

            entity.Property(e => e.Peso).HasColumnType("decimal(16, 2)");

            entity.Property(e => e.UsuarioModificacion)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.UsuarioRegistro)
                .HasMaxLength(20)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TasasComision> entity);
    }
}
