// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using IDCL.AVGUST.SIP.Entity.Pedido;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

#nullable disable

namespace IDCL.AVGUST.SIP.Contexto.DataPedido.Configurations
{
    public partial class ExpPedidoCabConfiguration : IEntityTypeConfiguration<PedidoCab>
    {
        public void Configure(EntityTypeBuilder<PedidoCab> entity)
        {
            entity.HasKey(e => new { e.IdPedido, e.IdEmpresa, e.IdLocal }).HasName("PK_exp_PedidoCab_1");
            entity.ToTable("exp_PedidoCab");
            entity.HasIndex(e => new { e.CodPedidoCad, e.IdLocal, e.IdEmpresa }, "IX_CodPedidoCab").IsUnique();
            entity.Property(e => e.IdPedido).ValueGeneratedOnAdd().HasColumnName("idPedido");
            entity.Property(e => e.IdEmpresa).HasColumnName("idEmpresa");
            entity.Property(e => e.IdLocal).HasColumnName("idLocal");
            entity.Property(e => e.AlmacenIngreso).HasComment("Almacen de Ingreso de Contenedor");
            entity.Property(e => e.Aprobacion).HasDefaultValueSql("((0))");
            entity.Property(e => e.Barco).HasMaxLength(100).IsUnicode(false);
            entity.Property(e => e.CodPedidoCad).HasMaxLength(20).IsUnicode(false).HasColumnName("codPedidoCad");
            entity.Property(e => e.Contacto).HasMaxLength(50).IsUnicode(false);
            entity.Property(e => e.Contenedor).HasMaxLength(50).IsUnicode(false).HasComment("Contenedor");
            entity.Property(e => e.Correo).HasMaxLength(200);
            entity.Property(e => e.CreditoDocumento).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.CreditoFacturas).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.CreditoLetras).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.DsctoProntoPago).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Estado).HasMaxLength(1).IsUnicode(false).HasDefaultValueSql("('P')").HasComment("Estado de Pedido P=Pendiente, C=Cerrado");
            entity.Property(e => e.Eta).HasColumnType("datetime").HasComment("Fecha Estimada de Llegada");
            entity.Property(e => e.Etd).HasColumnType("datetime").HasComment("Fecha Estimada de Salida");
            entity.Property(e => e.FecFactura).HasColumnType("smalldatetime").HasColumnName("fecFactura");
            entity.Property(e => e.Fecha).HasColumnType("smalldatetime");
            entity.Property(e => e.FechaEntrega).HasColumnType("datetime");
            entity.Property(e => e.FechaFinReserva).HasColumnType("smalldatetime");
            entity.Property(e => e.FechaGen).HasColumnType("smalldatetime");
            entity.Property(e => e.FechaInspeccion).HasColumnType("datetime").HasComment("Fecha de Inspeccion");
            entity.Property(e => e.FechaModificacion).HasColumnType("smalldatetime").HasColumnName("fechaModificacion");
            entity.Property(e => e.FechaPosic).HasColumnType("datetime").HasComment("Fecha de Posicionamiento Contenedor");
            entity.Property(e => e.FechaRegistro).HasColumnType("smalldatetime").HasColumnName("fechaRegistro");
            entity.Property(e => e.HorarioEntrega).HasMaxLength(100).IsUnicode(false);
            entity.Property(e => e.IdAgenciaEnvio).HasColumnName("idAgenciaEnvio");
            entity.Property(e => e.IdBlEmision).HasColumnName("idBlEmision").HasComment("id Ejemplo SEA WILL BILL");
            entity.Property(e => e.IdBroker).HasColumnName("idBroker").HasComment("id de Broker");
            entity.Property(e => e.IdCanalVenta).HasColumnName("idCanalVenta");
            entity.Property(e => e.IdCondicion).HasColumnName("idCondicion");
            entity.Property(e => e.IdConsFitosanitario).HasColumnName("idConsFitosanitario").HasComment("id de Consignatario FitoSanitario");
            entity.Property(e => e.IdConsignatario).HasColumnName("idConsignatario").HasComment("id de Consignatario");
            entity.Property(e => e.IdContacto).HasColumnName("idContacto");
            entity.Property(e => e.IdDestino).HasColumnName("idDestino").HasComment("id de Destino Honk Kong");
            entity.Property(e => e.IdDireccion).HasColumnName("idDireccion");
            entity.Property(e => e.IdDivision).HasColumnName("idDivision");
            entity.Property(e => e.IdEstablecimiento).HasColumnName("idEstablecimiento").HasComment("Zona de Trabajo");
            entity.Property(e => e.IdFacturar).HasColumnName("idFacturar").HasComment("id para Facturar");
            entity.Property(e => e.IdFlete).HasColumnName("idFlete").HasComment("id Flete Ejemplo Collect");
            entity.Property(e => e.IdFormaPago).HasColumnName("idFormaPago");
            entity.Property(e => e.IdIncoterms).HasColumnName("idIncoterms").HasComment("Incoterms FOB CALLAO");
            entity.Property(e => e.IdIncotermsPrecio).HasColumnName("idIncotermsPrecio");
            entity.Property(e => e.IdListaPrecio).HasColumnName("idListaPrecio");
            entity.Property(e => e.IdMoneda).HasMaxLength(2).IsUnicode(false).HasColumnName("idMoneda");
            entity.Property(e => e.IdMonedaLineaCredito).HasMaxLength(2).IsUnicode(false).HasColumnName("idMonedaLineaCredito");
            entity.Property(e => e.IdNaviera).HasColumnName("idNaviera").HasComment("Naviera");
            entity.Property(e => e.IdNotificar).HasColumnName("idNotificar").HasComment("id Notificar a las partes");
            entity.Property(e => e.IdOperador).HasColumnName("idOperador").HasComment("Operador Logistico");
            entity.Property(e => e.IdOrigen).HasColumnName("idOrigen").HasComment("id de Origen  Ejemplo Callao Peru");
            entity.Property(e => e.IdPaisDestino).HasColumnName("idPaisDestino").HasComment("Pais Destino");
            entity.Property(e => e.IdPaisOrigen).HasColumnName("idPaisOrigen").HasComment("Pais Origen");
            entity.Property(e => e.IdPedidoEnlace).HasColumnName("idPedidoEnlace");
            entity.Property(e => e.IdSemanaEmbarque).HasColumnName("idSemanaEmbarque").HasComment("id de Semana");
            entity.Property(e => e.IdSucursalCliente).HasColumnName("idSucursalCliente");
            entity.Property(e => e.IdTipCondicion).HasColumnName("idTipCondicion");
            entity.Property(e => e.IdTipoCompra).HasColumnName("idTipoCompra").HasComment("id MG");
            entity.Property(e => e.IdTransporte).HasColumnName("idTransporte");
            entity.Property(e => e.IdVendedor).HasColumnName("idVendedor");
            entity.Property(e => e.IdZona).HasColumnName("idZona").HasComment("Zona de Trabajo");
            entity.Property(e => e.IndAgencia).HasColumnName("indAgencia");
            entity.Property(e => e.IndBonificacion).HasColumnName("indBonificacion");
            entity.Property(e => e.IndCotPed).HasMaxLength(1).IsUnicode(false).HasColumnName("indCotPed").IsFixedLength();
            entity.Property(e => e.IndDsctoProntoPago).HasColumnName("indDsctoProntoPago");
            entity.Property(e => e.IndFechaFinReserva).HasColumnName("indFechaFinReserva");
            entity.Property(e => e.IndObsCredito).HasColumnName("indObsCredito");
            entity.Property(e => e.IndObsStock).HasColumnName("indObsStock");
            entity.Property(e => e.Indicaciones).HasMaxLength(500).IsUnicode(false);
            entity.Property(e => e.LetraNoAceptadas).HasColumnType("decimal(18, 3)");
            entity.Property(e => e.LetraProtestadas).HasColumnType("decimal(18, 3)");
            entity.Property(e => e.LineaCredito).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.LineaDisponible).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.MensajeAprobacion).HasMaxLength(200).IsUnicode(false).HasDefaultValueSql("('')");
            entity.Property(e => e.MensajeAprobacionPrecios).HasMaxLength(200).IsUnicode(false);
            entity.Property(e => e.NroBl).HasMaxLength(40).IsUnicode(false).HasColumnName("nroBl");
            entity.Property(e => e.NroDam).HasMaxLength(40).IsUnicode(false).HasColumnName("nroDam");
            entity.Property(e => e.NroDocReferencia).HasMaxLength(50).IsUnicode(false).HasColumnName("nroDocReferencia");
            entity.Property(e => e.NroFactura).HasMaxLength(20).IsUnicode(false).HasColumnName("nroFactura");
            entity.Property(e => e.NroFacturaGen).HasMaxLength(20).IsUnicode(false).HasColumnName("nroFacturaGen");
            entity.Property(e => e.NroGuia).HasMaxLength(50).IsUnicode(false).HasComment("Numero de Guia de Despacho");
            entity.Property(e => e.NroGuiaGen).HasMaxLength(20).IsUnicode(false);
            entity.Property(e => e.ObsCredito).HasMaxLength(200).IsUnicode(false);
            entity.Property(e => e.ObsStock).HasMaxLength(200).IsUnicode(false);
            entity.Property(e => e.Observacion).HasMaxLength(500).IsUnicode(false);
            entity.Property(e => e.OrdenDeCompraNum).HasMaxLength(20).IsUnicode(false);
            entity.Property(e => e.PorDscto).HasColumnType("decimal(10, 2)").HasColumnName("porDscto");
            entity.Property(e => e.PrecintoAduana).HasMaxLength(50).IsUnicode(false).HasComment("Precinto Aduana");
            entity.Property(e => e.PrecintoNaviera).HasMaxLength(50).IsUnicode(false).HasComment("Precinto Naviera");
            entity.Property(e => e.PrecintoOperador).HasMaxLength(50).IsUnicode(false).HasComment("Precinto Operador");
            entity.Property(e => e.PrecintoOtro).HasMaxLength(50).IsUnicode(false).HasComment("Precinto Otros");
            entity.Property(e => e.PrecintoSenasa).HasMaxLength(50).IsUnicode(false).HasComment("Precinto Senasa");
            entity.Property(e => e.PuertoDestino).HasMaxLength(30).IsUnicode(false);
            entity.Property(e => e.PuertoOrigen).HasMaxLength(30).IsUnicode(false);
            entity.Property(e => e.PuntoLlegada).HasMaxLength(400).IsUnicode(false);
            entity.Property(e => e.PuntoPartida).HasMaxLength(400).IsUnicode(false);
            entity.Property(e => e.Referencia).HasMaxLength(250);
            entity.Property(e => e.Reserva).HasMaxLength(50).IsUnicode(false).HasComment("Numero de Reserva / Booking");
            entity.Property(e => e.Telefono).HasMaxLength(100);
            entity.Property(e => e.TermografosNum).HasMaxLength(50).IsUnicode(false).HasComment("Numero de Termografo");
            entity.Property(e => e.TermografosNum2).HasMaxLength(50).IsUnicode(false).HasComment("Termografo 2");
            entity.Property(e => e.TermografosUbi).HasMaxLength(50).IsUnicode(false).HasComment("Ubicacion de Termografo");
            entity.Property(e => e.TermografosUbi2).HasMaxLength(50).IsUnicode(false).HasComment("Ubicacion de Termografo2");
            entity.Property(e => e.TipCambio).HasColumnType("decimal(5, 3)").HasColumnName("tipCambio");
            entity.Property(e => e.Tipo).HasComment("0 = Nacional 1 = Exportacion");
            entity.Property(e => e.TipoGeneracion).HasMaxLength(1).IsUnicode(false).HasColumnName("tipoGeneracion");
            entity.Property(e => e.TotDscto1).HasColumnType("decimal(12, 2)").HasColumnName("totDscto1");
            entity.Property(e => e.TotDscto2).HasColumnType("decimal(12, 2)").HasColumnName("totDscto2");
            entity.Property(e => e.TotDscto3).HasColumnType("decimal(12, 2)").HasColumnName("totDscto3");
            entity.Property(e => e.TotIgv).HasColumnType("decimal(12, 2)").HasColumnName("totIgv");
            entity.Property(e => e.TotIsc).HasColumnType("decimal(12, 2)").HasColumnName("totIsc");
            entity.Property(e => e.TotTotal).HasColumnType("decimal(12, 2)").HasColumnName("totTotal");
            entity.Property(e => e.TotsubTotal).HasColumnType("decimal(12, 2)").HasColumnName("totsubTotal");
            entity.Property(e => e.UbigeoCot).HasMaxLength(10);
            entity.Property(e => e.UsuarioGen).HasMaxLength(30).IsUnicode(false);
            entity.Property(e => e.UsuarioModificacion).HasMaxLength(30).IsUnicode(false);
            entity.Property(e => e.UsuarioRegistro).HasMaxLength(30).IsUnicode(false);
            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PedidoCab> entity);
    }
}
