// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using IDCL.AVGUST.SIP.Entity.Pedido;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

#nullable disable

namespace IDCL.AVGUST.SIP.Contexto.DataPedido.Configurations
{
    public partial class TipoCambioConfiguration : IEntityTypeConfiguration<TipoCambio>
    {
        public void Configure(EntityTypeBuilder<TipoCambio> entity)
        {
            entity.ToTable("TipoCambio");
            entity.HasKey(e => new { e.IdMoneda, e.IdCambio });
            entity.HasIndex(e => new { e.IdMoneda, e.FecCambio }, "IX_TipoCambio").IsUnique();
            entity.Property(e => e.IdMoneda).HasMaxLength(2).IsUnicode(false).HasColumnName("idMoneda").IsFixedLength();
            entity.Property(e => e.IdCambio).ValueGeneratedOnAdd().HasColumnName("idCambio");
            entity.Property(e => e.FecCambio).HasColumnType("smalldatetime").HasColumnName("fecCambio");
            entity.Property(e => e.FechaModificacion).HasColumnType("smalldatetime");
            entity.Property(e => e.FechaRegistro).HasColumnType("smalldatetime");
            entity.Property(e => e.UsuarioModificacion).HasMaxLength(20).IsUnicode(false);
            entity.Property(e => e.UsuarioRegistro).HasMaxLength(20).IsUnicode(false);
            entity.Property(e => e.ValCompra).HasColumnType("decimal(10, 3)").HasColumnName("valCompra");
            entity.Property(e => e.ValCompraCaja).HasColumnType("decimal(6, 4)").HasColumnName("valCompraCaja");
            entity.Property(e => e.ValVenta).HasColumnType("decimal(10, 3)").HasColumnName("valVenta");
            entity.Property(e => e.ValVentaCaja).HasColumnType("decimal(6, 4)").HasColumnName("valVentaCaja");
            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TipoCambio> entity);
    }
}
