// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using IDCL.AVGUST.SIP.Contexto2.IDCL.AVGUST.SIP.Contexto2;
using IDCL.AVGUST.SIP.Contexto2.IDCL.AVGUST.SIP.Entity.Avgust;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace IDCL.AVGUST.SIP.Contexto2.IDCL.AVGUST.SIP.Contexto2.Configurations
{
    public partial class OpcionConfiguration : IEntityTypeConfiguration<Opcion>
    {
        public void Configure(EntityTypeBuilder<Opcion> entity)
        {
            entity.ToTable("Opcion");

            entity.Property(e => e.Icono)
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasColumnName("icono");

            entity.Property(e => e.Nombre)
                .HasMaxLength(150)
                .IsUnicode(false);

            entity.Property(e => e.Type)
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasColumnName("type");

            entity.Property(e => e.Url)
                .HasMaxLength(150)
                .IsUnicode(false);

            entity.HasOne(d => d.IdOpcionRefNavigation)
                .WithMany(p => p.InverseIdOpcionRefNavigation)
                .HasForeignKey(d => d.IdOpcionRef)
                .HasConstraintName("FK_Opcion_Opcion");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Opcion> entity);
    }
}
