// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using IDCL.AVGUST.SIP.Entity.Pedido;
using Microsoft.EntityFrameworkCore;
#nullable enable

namespace IDCL.AVGUST.SIP.Contexto.DataPedido
{
    public partial class DbPedidoContext : DbContext
    {
        public DbPedidoContext()
        {
        }

        public DbPedidoContext(DbContextOptions<DbPedidoContext> options)
            : base(options)
        {
        }

        public virtual DbSet<PedidoCab> PedidoCabs { get; set; } = null!;
        public virtual DbSet<PedidoDet> PedidoDets { get; set; } = null!;
        public virtual DbSet<Persona> Personas { get; set; } = null!;
        public virtual DbSet<TipoCambio> TipoCambios { get; set; } = null!;


        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
        modelBuilder.ApplyConfiguration(new Configurations.ExpPedidoCabConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ExpPedidoDetConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.PersonaConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.TipoCambioConfiguration());

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
