// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable


namespace IDCL.AVGUST.SIP.Entity.Calculator
{
    public class ArticuloServ
    {
        public int IdEmpresa { get; set; }
        public int IdArticulo { get; set; }
        public string? CodArticulo { get; set; }
        public string? NomArticulo { get; set; }
        public string? NomArticuloEng { get; set; }
        public string? NomArticuloLargo { get; set; }
        public string? NomCorto { get; set; }
        public bool? IndCodBarra { get; set; }
        public string? CodBarra { get; set; }
        public string? CodBarra2 { get; set; }
        public string? CodBarra3 { get; set; }
        public string? CodBarra4 { get; set; }
        public string? CodBarra5 { get; set; }
        public int? CodTipoMedAlmacen { get; set; }
        public int? CodUniMedAlmacen { get; set; }
        public int? IdTipoMedEnvase { get; set; }
        public int? IdUniMedEnvase { get; set; }
        public int? CodTipoMedPresentacion { get; set; }
        public int? CodUniMedPresentacion { get; set; }
        public decimal? Contenido { get; set; }
        public decimal? Capacidad { get; set; }
        public decimal? PesoUnitario { get; set; }
        public int? IdTipoArticulo { get; set; }
        public string? CodCategoria { get; set; }
        public bool? IndLineaVenta { get; set; }
        public string? CodLineaVenta { get; set; }
        public int? IdTipo { get; set; }
        public bool? Combinar { get; set; }
        public int? IdArticuloBase { get; set; }
        public int? IdPresentacion { get; set; }
        public string? NombreReal { get; set; }
        public string? NombreImagen { get; set; }
        public string? Extension { get; set; }
        public int? CodColor { get; set; }
        public int? CodMaterial { get; set; }
        public int? CodCapellada { get; set; }
        public int? CodTaco { get; set; }
        public int? CodEstilo { get; set; }
        public int? CodForro { get; set; }
        public int? CodPlanta { get; set; }
        public int? CodEstacion { get; set; }
        public string? Horma { get; set; }
        public decimal? MedAncho { get; set; }
        public decimal? MedLargo { get; set; }
        public decimal? AltPlataforma { get; set; }
        public decimal? Compartimiento { get; set; }
        public decimal? BolInterno { get; set; }
        public decimal? BolExterno { get; set; }
        public bool? IndCuero { get; set; }
        public int? CodSerie { get; set; }
        public int? CodModelo { get; set; }
        public int? CodMarca { get; set; }
        public string? Sku { get; set; }
        public bool? IndDetraccion { get; set; }
        public string? TipDetraccion { get; set; }
        public bool? IndCodSunat { get; set; }
        public string? CodigoSunat { get; set; }
        public bool FlagActivo { get; set; }
        public DateTime? FecCese { get; set; }
        public int? TipoAfectacion { get; set; }
        public bool? IndAfectoIgv { get; set; }
        public bool? IndAfectoIsc { get; set; }
        public bool? IndConcepto { get; set; }
        public int? IdConcepto { get; set; }
        public bool? IndCodEquivalente { get; set; }
        public string? CodEquivalente { get; set; }
        public bool? IndMedida { get; set; }
        public decimal? Ancho { get; set; }
        public decimal? Largo { get; set; }
        public decimal? Calibre { get; set; }
        public decimal? Gramaje { get; set; }
        public string? DesColor { get; set; }
        public int Idformato { get; set; }
        public bool? IndCompraDemasia { get; set; }
        public decimal? PorcentajeDemasia { get; set; }
        public int? IdPartidaPresupuestal { get; set; }
        public decimal? DensidadDesde { get; set; }
        public decimal? DensidadHasta { get; set; }
        public decimal? PhDesde { get; set; }
        public decimal? PhHasta { get; set; }
        public string? UsuarioRegistro { get; set; }
        public DateTime? FechaRegistro { get; set; }
        public string? UsuarioModificacion { get; set; }
        public DateTime? FechaModificacion { get; set; }

        public ArticuloCategorium? ArticuloCategorium { get; set; }
        public List<ListaPrecioItem> ListaPrecioItems { get; set; }
        public List<RentabilidadComision> RentabilidadComisions { get; set; }
    }
}