// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

namespace IDCL.AVGUST.SIP.Entity.Calculator
{
    public class ArticuloCategorium
    {

        public int IdEmpresa { get; set; }
        public int IdTipoArticulo { get; set; }
        public string CodCategoria { get; set; } = null!;
        public string? CodCategoriaAnte { get; set; }
        public string NombreCategoria { get; set; } = null!;
        public int NumNivel { get; set; }
        public string IndUltimoNivel { get; set; } = null!;
        public string? CodCategoriaSup { get; set; }
        public bool? IndCuenta { get; set; }
        public string? NumVerPlanCuentas { get; set; }
        public string? CodCuentaAdm { get; set; }
        public string? CodCuentaVta { get; set; }
        public string? CodCuentaPro { get; set; }
        public string? CodCuentaConsumo { get; set; }
        public string? CodCuentaVenta { get; set; }
        public string? CodCuentaVentaRelacionada { get; set; }
        public string? CodCuentaVenta12 { get; set; }
        public string? CodCuentaCompra { get; set; }
        public string? CodCuentaPorRecibir { get; set; }
        public int? IdTipoArticuloAsoc { get; set; }
        public string? CodCategoriaAsoc { get; set; }
        public bool? IndManejaUnmMayor { get; set; }
        public bool? IndManejaUnmMenor { get; set; }
        public string? UsuarioRegistro { get; set; }
        public DateTime? FechaRegistro { get; set; }
        public string? UsuarioModificacion { get; set; }
        public DateTime? FechaModificacion { get; set; }

        public List<ArticuloServ> ArticuloServs { get; set; }
    }
}