// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

namespace IDCL.AVGUST.SIP.Entity.Calculator
{
    public class ListaPrecioItem
    {
        public int IdEmpresa { get; set; }
        public int IdListaPrecio { get; set; }
        public int Item { get; set; }
        /// <summary>
        /// Tipo de Articulos
        /// </summary>
        public int IdTipoArticulo { get; set; }
        /// <summary>
        /// Articulo
        /// </summary>
        public int IdArticulo { get; set; }
        public decimal PrecioBruto { get; set; }
        public decimal PorDscto1 { get; set; }
        public decimal PorDscto2 { get; set; }
        public decimal PorDscto3 { get; set; }
        public decimal MontoDscto1 { get; set; }
        public decimal MontoDscto2 { get; set; }
        public decimal MontoDscto3 { get; set; }
        public decimal PrecioValorVenta { get; set; }
        /// <summary>
        /// 1= Activo , 0 = No Activo
        /// </summary>
        public bool Flgisc { get; set; }
        /// <summary>
        /// P=Porcentaje,L=Litro,N=Ninguno
        /// </summary>
        public string TipoImpSelectivo { get; set; } = null!;
        /// <summary>
        /// 25%,2.50 x Litro, N = 0
        /// </summary>
        public decimal Porisc { get; set; }
        public decimal Isc { get; set; }
        /// <summary>
        /// 1=Activo, 0 = No Activo
        /// </summary>
        public bool Flgigv { get; set; }
        public decimal Porigv { get; set; }
        public decimal Igv { get; set; }
        public decimal PrecioVenta { get; set; }
        public decimal? Capacidad { get; set; }
        public decimal? Contenido { get; set; }
        public decimal? PrecioVentaConte { get; set; }
        public decimal? PrecioBrutoConte { get; set; }
        public bool Estado { get; set; }
        public bool? Flgpromocion { get; set; }
        public string? UsuarioRegistro { get; set; }
        public DateTime? FechaRegistro { get; set; }
        public string? UsuarioModificacion { get; set; }
        public DateTime? FechaModificacion { get; set; }

        public ArticuloServ Id { get; set; } = null!;
        public ListaPrecio IdNavigation { get; set; } = null!;
        public List<ListaPrecioItemDet> ListaPrecioItemDets { get; set; }
    }
}