// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

namespace IDCL.AVGUST.SIP.Entity.Calculator
{
    public partial class ListaPrecioItemDet
    {
        public int IdEmpresa { get; set; }
        public int IdListaPrecio { get; set; }
        public int Item { get; set; }
        public int Iditem { get; set; }
        public int? IdTipoArticulo { get; set; }
        public int? IdArticulo { get; set; }
        public decimal? DesdeCantidad { get; set; }
        public decimal? PrecioBruto { get; set; }
        public decimal? PrecioVenta { get; set; }
        public string? UsuarioRegistro { get; set; }
        public DateTime? FechaRegistro { get; set; }
        public string? UsuarioModificacion { get; set; }
        public DateTime? FechaModificacion { get; set; }

        public ListaPrecioItem ListaPrecioItem { get; set; }
    }
}