// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

namespace IDCL.AVGUST.SIP.Entity.Calculator
{
    public class RentabilidadComision
    {
        public int IdEmpresa { get; set; }
        public string Anio { get; set; } = null!;
        public string Mes { get; set; } = null!;
        public int IdArticulo { get; set; }
        //public int IdAlmacen { get; set; }
        public decimal? Porcentaje { get; set; }
        public decimal? CategoriaRes { get; set; }
        public decimal? CostoUnit { get; set; }
        public string? UsuarioRegistro { get; set; }
        public DateTime? FechaRegistro { get; set; }
        public string? UsuarioModificacion { get; set; }
        public DateTime? FechaModificacion { get; set; }

        public ArticuloServ Id { get; set; } = null!;
    }
}