// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

namespace IDCL.AVGUST.SIP.Entity.Calculator
{
    public class SimuladorPedido
    {
        public int IdPedido { get; set; }
        public DateTime FechaOperacion { get; set; }
        public decimal ImporteTotal { get; set; }
        public decimal Igv { get; set; }
        public decimal VentaTotal { get; set; }
        public decimal ComisionPercent { get; set; }
        public decimal ComisionMonto { get; set; }

        public List<SimuladorPedidoItem> SimuladorPedidoItems { get; set; }
    }
}