// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

namespace IDCL.AVGUST.SIP.Entity.Calculator
{
    public class TasasComision
    {
        public string Categoria { get; set; }
        public decimal? LimiteIni { get; set; }
        public decimal? LimiteFin { get; set; }
        public decimal? Peso { get; set; }
        public string? UsuarioRegistro { get; set; }
        public DateTime? FechaRegistro { get; set; }
        public string? UsuarioModificacion { get; set; }
        public DateTime? FechaModificacion { get; set; }
    }
}