// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IDCL.AVGUST.SIP.Contexto.IDCL.AVGUST.SIP.Entity.Avgust
{
    public partial class Clase
    {
        public int IdClase { get; set; }
        public string Descripcion { get; set; }
        public bool? Estado { get; set; }
        public int? IdTipoProducto { get; set; }

        public virtual IdTipoProducto IdTipoProductoNavigation { get; set; }
    }
}