// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IDCL.AVGUST.SIP.Contexto.IDCL.AVGUST.SIP.Entity.Avgust
{
    public partial class IdTipoProducto
    {
        public IdTipoProducto()
        {
            Clases = new HashSet<Clase>();
        }

        public int IdTipoProducto1 { get; set; }
        public string NomTipoProducto { get; set; }
        public bool? Estado { get; set; }

        public virtual ICollection<Clase> Clases { get; set; }
    }
}