// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using IDCL.Tacama.Core.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

#nullable disable

namespace IDCL.Tacama.Core.Contexto.Configurations
{
    public partial class TramaHistoricoConfiguration : IEntityTypeConfiguration<TramaHistorico>
    {
        public void Configure(EntityTypeBuilder<TramaHistorico> entity)
        {
            entity.ToTable("TramaHistorico");

            entity.Property(e => e.FechaHora).HasColumnType("datetime");

            entity.Property(e => e.Latitud)
                .HasColumnType("decimal(12, 9)")
                .HasColumnName("latitud");

            entity.Property(e => e.Longitud)
                .HasColumnType("decimal(12, 9)")
                .HasColumnName("longitud");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TramaHistorico> entity);
    }
}
