// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using IDCL.Tacama.Core.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

#nullable disable

namespace IDCL.Tacama.Core.Contexto.Configurations
{
    public partial class UsuarioRolConfiguration : IEntityTypeConfiguration<UsuarioRol>
    {
        public void Configure(EntityTypeBuilder<UsuarioRol> entity)
        {
            entity.HasKey(e => new { e.IdPersona, e.IdRol, e.IdEmpresa })
                .HasName("XPKUsuarioRol");

            entity.ToTable("UsuarioRol");

            entity.Property(e => e.FechaActualizacion).HasColumnType("datetime");

            entity.Property(e => e.FechaRegistro).HasColumnType("datetime");

            entity.Property(e => e.UsuarioActualizacion).HasMaxLength(50);

            entity.Property(e => e.UsuarioRegistro).HasMaxLength(50);

            entity.HasOne(d => d.IdPersonaNavigation)
                .WithMany(p => p.UsuarioRols)
                .HasForeignKey(d => d.IdPersona)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("R_16");

            entity.HasOne(d => d.IdRolNavigation)
                .WithMany(p => p.UsuarioRols)
                .HasForeignKey(d => d.IdRol)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("R_17");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<UsuarioRol> entity);
    }
}
