// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using IDCL.Tacama.Core.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

#nullable disable

namespace IDCL.Tacama.Core.Contexto.Configurations
{
    public partial class UsuarioConfiguration : IEntityTypeConfiguration<UsuarioTacama>
    {
        public void Configure(EntityTypeBuilder<UsuarioTacama> entity)
        {
            entity.HasKey(e => e.IdPersona)
                .HasName("XPKUsuario");

            entity.ToTable("Usuario");

            entity.Property(e => e.IdPersona).ValueGeneratedNever();

            entity.Property(e => e.Clave).HasMaxLength(256);

            entity.Property(e => e.ClaveOtros)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.Credencial).HasMaxLength(50);

            entity.Property(e => e.Extension)
                .HasMaxLength(5)
                .IsUnicode(false);

            entity.Property(e => e.FechaModificacion).HasColumnType("datetime");

            entity.Property(e => e.FechaRegistro).HasColumnType("datetime");

            entity.Property(e => e.IndAdministrador).HasColumnName("indAdministrador");

            entity.Property(e => e.NombreCorto)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.NombreImagen)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.NombreReal)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.ServidorSalienteOtros)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.UsuarioModificacion).HasMaxLength(50);

            entity.Property(e => e.UsuarioRegistro).HasMaxLength(50);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<UsuarioTacama> entity);
    }
}
