// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IDCL.AVGUST.SIP.Contexto.IDCL.AVGUST.SIP.Entity.Avgust
{
    public partial class Articulo
    {

        public int IdArticulo { get; set; }
        public int? IdPais { get; set; }
        public string NombreComercial { get; set; }
        public int? IdTitularRegistro { get; set; }
        public string NroRegistro { get; set; }
        public int? IdTipoProducto { get; set; }
        public int? IdFormulador { get; set; }
        public int? IdGrupoQuimico { get; set; }
        public int? IdTipoFormulacion { get; set; }
        public bool FlgActivo { get; set; }
        //public Formulador? IdFormuladorNavigation { get; set; }
        public GrupoQuimico? IdGrupoQuimicoNavigation { get; set; }
        public Pai? IdPaisNavigation { get; set; }
        public TipoFormulacion IdTipoFormulacionNavigation { get; set; }
        public IdTipoProducto? IdTipoProductoNavigation { get; set; }
        public TitularRegistro? IdTitularRegistroNavigation { get; set; }
        public List<Caracteristica> Caracteristicas { get; set; }
        public List<Composicion> Composicions { get; set; }
        public List<Documento> Documentos { get; set; }
        public List<Uso> Usos { get; set; }


        public List<ProductoFabricante> ProductoFabricantes { get; set; }
        public List<ProductoFormulador> ProductoFormuladors { get; set; }

    }
}