// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IDCL.AVGUST.SIP.Contexto.IDCL.AVGUST.SIP.Entity.Avgust
{
    public partial class CientificoPlaga
    {
       

        public int IdNomCientificoPlaga { get; set; }
        public string NombreCientificoPlaga { get; set; }
        public bool estado { get; set; }
        public  List<Uso> Usos { get; set; }
    }
}