// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IDCL.AVGUST.SIP.Contexto.IDCL.AVGUST.SIP.Entity.Avgust
{
    public partial class Documento
    {
        public int IdArticulo { get; set; }
        public int IdItem { get; set; }
        public int? IdTipoDocumento { get; set; }
        public DateTime? Fecha { get; set; }
        public string NomDocumento { get; set; }

        public Articulo IdArticuloNavigation { get; set; }
        public TipoDocumento IdTipoDocumentoNavigation { get; set; }
    }
}