// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace IDCL.AVGUST.SIP.Contexto.IDCL.AVGUST.SIP.Entity.Avgust
{
    public partial class Fabricante
    {
        public int IdFabricante { get; set; }
        public string NombreFabricante { get; set; }
        public bool Estado { get; set; }

        public List<ProductoFabricante> ProductoFabricantes { get; set; }

    }
}