// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IDCL.AVGUST.SIP.Contexto.IDCL.AVGUST.SIP.Entity.Avgust
{
    public partial class Formulador
    {
      

        public int IdFormulador { get; set; }
        public string NomFormulador { get; set; }
        public bool estado { get; set; }
        public List<Articulo> Articulos { get; set; }
    }
}