// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace IDCL.AVGUST.SIP.Contexto.IDCL.AVGUST.SIP.Entity.Avgust
{
    public partial class GrupoQuimico
    {

        public int IdGrupoQuimico { get; set; }
        public string NomGrupoQuimico { get; set; }
        public bool estado { get; set; }
        public List<Articulo> Articulos { get; set; }
        public List<Composicion> Composiciones { get; set; }
    }
}