// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace IDCL.AVGUST.SIP.Contexto.IDCL.AVGUST.SIP.Entity.Avgust
{
    public partial class IngredienteActivo
    {

        public int IngredenteActivo { get; set; }
        public string NomIngredienteActivo { get; set; }
        public bool estado { get; set; }
        public  List<Composicion> Composicions { get; set; }
    }
}