// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IDCL.AVGUST.SIP.Contexto.IDCL.AVGUST.SIP.Entity.Avgust
{
    public partial class ProductoFabricante
    {
        public int IdArticulo { get; set; }
        public int IdFabricante { get; set; }

        public Articulo IdArticuloNavigation { get; set; }
        public Fabricante IdFabricanteNavigation { get; set; }
    }
}