// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IDCL.AVGUST.SIP.Contexto.IDCL.AVGUST.SIP.Entity.Avgust
{
    public partial class ProductoFormulador
    {
        public int IdProducto { get; set; }
        public int IdFormualdor { get; set; }

        public Articulo IdProductoNavigation { get; set; }

        public Formulador IdFormuladorNavigation { get; set; }

    }
}