// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IDCL.AVGUST.SIP.Contexto.IDCL.AVGUST.SIP.Entity.Avgust
{
    public partial class Uso
    {
        public int IdArticulo { get; set; }
        public int IdItem { get; set; }
        public int? IdCultivo { get; set; }
        public string NombreCientificoCultivo { get; set; }
        public int? IdNomCientificoPlaga { get; set; }
        public string Dosis { get; set; }

        public Articulo IdArticuloNavigation { get; set; }
        public Cultivo IdCultivoNavigation { get; set; }
        public CientificoPlaga IdNomCientificoPlagaNavigation { get; set; }
    }
}