// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IDCL.AVGUST.SIP.Contexto.IDCL.AVGUST.SIP.Entity.Avgust
{
    public partial class UsuarioPai
    {
        public int IdUsuario { get; set; }
        public int IdPais { get; set; }
        public bool? PorDefault { get; set; }

        public Pai IdPaisNavigation { get; set; }
        public Usuario IdUsuarioNavigation { get; set; }
    }
}