// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using IDCL.AVGUST.SIP.Contexto.IDCL.AVGUST.SIP.Contexto;
using IDCL.AVGUST.SIP.Contexto.IDCL.AVGUST.SIP.Entity.Avgust;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace IDCL.AVGUST.SIP.Contexto.IDCL.AVGUST.SIP.Contexto.Configurations
{
    public partial class CaracteristicaConfiguration : IEntityTypeConfiguration<Caracteristica>
    {
        public void Configure(EntityTypeBuilder<Caracteristica> entity)
        {
            entity.HasKey(e => new { e.IdArticulo, e.IdItem });

            entity.Property(e => e.IdArticulo).HasColumnName("idArticulo");

            entity.Property(e => e.IdItem).HasColumnName("idItem");

            entity.Property(e => e.IdAplicacion).HasColumnName("idAplicacion");

            entity.Property(e => e.IdClase).HasColumnName("idClase");

            entity.Property(e => e.IdToxicologica).HasColumnName("idToxicologica");

            entity.HasOne(d => d.IdAplicacionNavigation)
                .WithMany(p => p.Caracteristicas)
                .HasForeignKey(d => d.IdAplicacion)
                .HasConstraintName("FK_Caracteristicas_Aplicacion");

            entity.HasOne(d => d.IdArticuloNavigation)
                .WithMany(p => p.Caracteristicas)
                .HasForeignKey(d => d.IdArticulo)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Caracteristicas_Articulo");

            entity.HasOne(d => d.IdClaseNavigation)
                .WithMany(p => p.Caracteristicas)
                .HasForeignKey(d => d.IdClase)
                .HasConstraintName("FK_Caracteristicas_Clase");

            entity.HasOne(d => d.IdToxicologicaNavigation)
                .WithMany(p => p.Caracteristicas)
                .HasForeignKey(d => d.IdToxicologica)
                .HasConstraintName("FK_Caracteristicas_Toxicologica");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Caracteristica> entity);
    }
}
