// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using IDCL.AVGUST.SIP.Contexto.IDCL.AVGUST.SIP.Entity.Avgust;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace IDCL.AVGUST.SIP.Contexto.IDCL.AVGUST.SIP.Contexto.Configurations
{
    public partial class ClaseConfiguration : IEntityTypeConfiguration<Clase>
    {
        public void Configure(EntityTypeBuilder<Clase> entity)
        {
            entity.HasKey(e => e.IdClase);

            entity.ToTable("Clase");

            entity.Property(e => e.IdClase).HasColumnName("idClase");

            entity.Property(e => e.Descripcion)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.estado)
                .IsRequired()
                .HasColumnName("estado")
                .HasDefaultValueSql("((1))");
            entity.HasOne(d => d.IdTipoProductoNavigation)
                .WithMany(p => p.Clases)
                .HasForeignKey(d => d.IdTipoProducto)
                .OnDelete(DeleteBehavior.ClientSetNull);


            //        entity.HasOne(d => d.IdClaseNavigation)
            //.WithMany(p => p.IdTipoProductos)
            //.HasForeignKey(d => d.IdClase)
            //.OnDelete(DeleteBehavior.ClientSetNull)
            //.HasConstraintName("FK_idTipoProducto_Clase");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Clase> entity);
    }
}
