// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using IDCL.AVGUST.SIP.Contexto.IDCL.AVGUST.SIP.Contexto;
using IDCL.AVGUST.SIP.Contexto.IDCL.AVGUST.SIP.Entity.Avgust;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace IDCL.AVGUST.SIP.Contexto.IDCL.AVGUST.SIP.Contexto.Configurations
{
    public partial class GrupoQuimicoConfiguration : IEntityTypeConfiguration<GrupoQuimico>
    {
        public void Configure(EntityTypeBuilder<GrupoQuimico> entity)
        {
            entity.HasKey(e => e.IdGrupoQuimico);

            entity.ToTable("GrupoQuimico");

            entity.Property(e => e.IdGrupoQuimico).HasColumnName("idGrupoQuimico");

            entity.Property(e => e.estado)
                .IsRequired()
                .HasColumnName("estado")
                .HasDefaultValueSql("((1))");

            entity.Property(e => e.NomGrupoQuimico)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("nomGrupoQuimico");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<GrupoQuimico> entity);
    }
}
