// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using IDCL.AVGUST.SIP.Contexto.IDCL.AVGUST.SIP.Contexto;
using IDCL.AVGUST.SIP.Contexto.IDCL.AVGUST.SIP.Entity.Avgust;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace IDCL.AVGUST.SIP.Contexto.IDCL.AVGUST.SIP.Contexto.Configurations
{
    public partial class IdTipoProductoConfiguration : IEntityTypeConfiguration<IdTipoProducto>
    {
        public void Configure(EntityTypeBuilder<IdTipoProducto> entity)
        {
            entity.HasKey(e => e.IdTipoProducto1);

            entity.ToTable("idTipoProducto");

            entity.Property(e => e.IdTipoProducto1).HasColumnName("idTipoProducto");

            entity.Property(e => e.estado)
                .IsRequired()
                .HasColumnName("estado")
                .HasDefaultValueSql("((1))");

            entity.Property(e => e.NomTipoProducto)
               .HasMaxLength(200)
               .IsUnicode(false)
               .HasColumnName("nomTipoProducto");



            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<IdTipoProducto> entity);
    }
}
