// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using IDCL.AVGUST.SIP.Contexto.IDCL.AVGUST.SIP.Contexto;
using IDCL.AVGUST.SIP.Contexto.IDCL.AVGUST.SIP.Entity.Avgust;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace IDCL.AVGUST.SIP.Contexto.IDCL.AVGUST.SIP.Contexto.Configurations
{
    public partial class IngredienteActivoConfiguration : IEntityTypeConfiguration<IngredienteActivo>
    {
        public void Configure(EntityTypeBuilder<IngredienteActivo> entity)
        {
            entity.HasKey(e => e.IngredenteActivo);

            entity.ToTable("IngredienteActivo");

            entity.Property(e => e.IngredenteActivo);

            entity.Property(e => e.NomIngredienteActivo)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("nomIngredienteActivo");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<IngredienteActivo> entity);
    }
}
