// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using IDCL.AVGUST.SIP.Contexto.IDCL.AVGUST.SIP.Entity.Avgust;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace IDCL.AVGUST.SIP.Contexto.IDCL.AVGUST.SIP.Contexto.Configurations
{
    public partial class ProductoFormuladorConfiguration : IEntityTypeConfiguration<ProductoFormulador>
    {
        public void Configure(EntityTypeBuilder<ProductoFormulador> entity)
        {
            entity.HasKey(e => new { e.IdProducto, e.IdFormualdor });

            entity.ToTable("ProductoFormulador");

            entity.HasOne(d => d.IdFormuladorNavigation)
                            .WithMany(p => p.ProductoFormuladors)
                            .HasForeignKey(d => d.IdFormualdor);

            entity.HasOne(d => d.IdProductoNavigation)
                .WithMany(p => p.ProductoFormuladors)
                .HasForeignKey(d => d.IdProducto);


            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ProductoFormulador> entity);
    }
}
