// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using IDCL.AVGUST.SIP.Contexto.IDCL.AVGUST.SIP.Contexto;
using IDCL.AVGUST.SIP.Contexto.IDCL.AVGUST.SIP.Entity.Avgust;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace IDCL.AVGUST.SIP.Contexto.IDCL.AVGUST.SIP.Contexto.Configurations
{
    public partial class TitularRegistroConfiguration : IEntityTypeConfiguration<TitularRegistro>
    {
        public void Configure(EntityTypeBuilder<TitularRegistro> entity)
        {
            entity.HasKey(e => e.IdTitularRegistro);

            entity.ToTable("TitularRegistro");

            entity.Property(e => e.IdTitularRegistro).HasColumnName("idTitularRegistro");

            entity.Property(e => e.estado)
                .IsRequired()
                .HasColumnName("estado")
                .HasDefaultValueSql("((1))");

            entity.Property(e => e.NomTitularRegistro)
                .HasMaxLength(250)
                .IsUnicode(false)
                .HasColumnName("nomTitularRegistro");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TitularRegistro> entity);
    }
}
