// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using IDCL.AVGUST.SIP.Entity.Calculator;
using Microsoft.EntityFrameworkCore;
#nullable enable

namespace IDCL.AVGUST.SIP.Contextos.IDCL.AVGUST.SIP.Contexto
{
    public partial class DbAvgustCalcContext : DbContext
    {
        public DbAvgustCalcContext()
        {
        }

        public DbAvgustCalcContext(DbContextOptions<DbAvgustCalcContext> options)
            : base(options)
        {
        }

        public virtual DbSet<ArticuloCategorium> ArticuloCategoria { get; set; } = null!;
        public virtual DbSet<ArticuloServ> ArticuloServs { get; set; } = null!;
        public virtual DbSet<ListaPrecio> ListaPrecios { get; set; } = null!;
        public virtual DbSet<ListaPrecioItem> ListaPrecioItems { get; set; } = null!;
        public virtual DbSet<RentabilidadComision> RentabilidadComisions { get; set; } = null!;
        public virtual DbSet<SimuladorPedido> SimuladorPedidos { get; set; } = null!;
        public virtual DbSet<SimuladorPedidoItem> SimuladorPedidoItems { get; set; } = null!;
        public virtual DbSet<TasasComision> TasasComisions { get; set; } = null!;
        public virtual DbSet<ListaPrecioItemDet> ListaPrecioItemDets { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ApplyConfiguration(new Configurations.ArticuloCategoriumConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.ArticuloServConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.ListaPrecioConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.ListaPrecioItemConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.ListaPrecioItemDetConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.RentabilidadComisionConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.SimuladorPedidoConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.SimuladorPedidoItemConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.TasasComisionConfiguration());

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
